version: '3.8'

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/auth-service
      - JWT_SECRET=your-secret-key
      - JWT_EXPIRES_IN=24h
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=http://localhost:3000/auth/google/callback
      - OPENID_ISSUER=http://keycloak:8080/realms/auth-service
      - OPENID_CLIENT_ID=auth-service-client
      - OPENID_CLIENT_SECRET=${OPENID_CLIENT_SECRET}
      - OPENID_CALLBACK_URL=http://localhost:3000/auth/openid/callback
      - FRONTEND_URL=http://localhost:3001
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - keycloak
      - redis
    networks:
      - auth-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - auth-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - auth-network

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongodb
    networks:
      - auth-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=dev-file
    ports:
      - "8080:8080"
    command: start-dev
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data: 